<!--Componente Card-->
<?php if(isset($productos)): ?> 
<!-- Si existe el array de productos, es porque estoy en el listado de productos, entonces hago el enlace al detalle. -->
<a href="<?php echo BASE_URL; ?>/detalle/<?= $producto->id ?>" class="d-flex flex-column w-25 m-1 card-product align-items-center" <?php echo $producto->stock == 1 ? "" : "card-disabled" ?>>

<?php else: ?> 
    <div class="d-flex flex-column w-25 m-1 card-product align-items-center"> <!-- Si no existe el array de productos, estoy en el detalle del producto, entonces solo muestro el div. -->
<?php endif ?>
<div><img src="<?= $producto->url ?>" alt="img_product_example" height="400" width="400"></div>
    <div class="d-flex flex-column  justify-content-center card-body">
        <h3 class= "fw-bold"><?= $producto->nombre ?></h3>
        <?php if(isset($productos)) :?>
            <?= substr(htmlspecialchars($producto->descripcion), 0, 40) ?>...
        <?php else : ?>
            <?= htmlspecialchars($producto->descripcion)?>
        <?php endif ?> <br></br>
            
        <?php if(!isset($productos)) :?>
            <p>tamanio <?= $producto->presentacion?></p>
        <?php endif ?>
       

        <p>stock:<span
         class="<?= $producto->stock== 1 ? "text-success" : "text-danger" ?>"><?= $producto->stock == 1 ? "disponible" : "no disponible" ?></span>
        </p>
        <p>precio:
            <?= $producto->precio?>
        </p>
        
        
        
        <?php if(!isset($productos)): ?> <!-- // Si no estoy en el listado de productos, estoy en el detalle, por lo tanto muestro el boton eliminar. -->
            <div><a href="<?php echo BASE_URL; ?>/eliminarProducto/<?= $producto->id ?>" class="btn btn-danger">Eliminar</a></div>
        <?php endif ?>
    </div>
    
<?php if(isset($productos)): ?> <!-- //Cierre del enlace si estoy en el listado de productos. -->
</a>

<?php else: ?> <!-- //Cierre del div si estoy en el detalle del producto. -->
</div>

<?php endif ?>