<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="style.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">




    <title>Tienda Millanel</title>
</head>
<body>
    <header>
        <nav class="d-flex container justify-content-between align-items-center">
            <a href="<?php echo BASE_URL; ?>/home"> <img src="<?php echo BASE_URL; ?>../img/img-logo-millanel.jpg" alt="logo-menu" height="100" width="100"></a>
             <ul class="d-flex flex-row gap-5">
            <li><a href="<?php echo BASE_URL; ?>/admin">Admin</a></li>
            <li><a href="<?php echo BASE_URL; ?>/showLoguin">Iniciar Sesión</a></li>
            </ul>
        </nav>
    </header>

    <main>

    <section class="d-flex flex-column align-items-center bg-primary">
    <h1 class="w-50 bg-warning text-center">Perfumes Millanel</h1>
    <h3 class="w-50 bg-danger text-center">Descubri todas las novedades que trae el catalogo Millanel de la nueva campania Vigencia de la campania del 15/09/2025 al 19/10/2025</h3>
    </section>

    <section class="d-flex flex-row flex-wrap w-100 bg-secondary justify-content-center">
          <?php foreach ($product as $element): ?>
            <?php require 'component/card.phtml' ?> <!--Trae toda la descripcion de la card-->
            <?php endforeach ?>
    </section>
    </main>
<footer class="text-center p-3">
    Copyright 2025, Javier Ignacio Rivarola - Micaela Jazmin Breijo
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>