<?php require_once './template/layout/header.phtml'; ?> <!--Trae el header-->
<seccion class="container my-5">
    <div class="card shadow-lg rounded mx-auto" style="max-width:420px;">
        <div class="card-body p-4">
            <h2 class="card-title text-center mb-4">Registro de usuario</h2>

            <form method="post" action="registrarse" novalidate>
                <div class="mb-3">
                    <label for="usuario" class="form-label">Usuario</label>
                    <input type="text" class="form-control" id="usuario" name="usuario" placeholder="Ingresa tu usuario" required autocomplete="username">
                </div>

                <div class="mb-3">
                    <label for="contrasenia" class="form-label">Contraseña</label>
                    <input type="password" class="form-control" id="contrasenia" name="contrasenia" placeholder="Ingresa tu contraseña" required autocomplete="new-password">
                </div>

                <div class="d-grid">
                    <button type="submit" class="btn boton-registrarse btn-lg" href="">Registrar</button>
                </div>
            </form>
        </div>
    </div>
</seccion>
<?php require_once './template/layout/footer.phtml'; ?>