<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="<?php echo BASE_URL;?>../css/style.css">
    
    <title>Tienda Millanel</title>
</head>
<body>
    <header>
        <nav class="d-flex justify-content-around align-items-center">
            <a href="<?php echo BASE_URL; ?>/home"> <img src="<?php echo BASE_URL; ?>../img/img-logo-millanel.jpg" alt="logo-menu" height="100" width="100"></a>
             <ul class="d-flex flex-row gap-5">
            <li><a href="<?php echo BASE_URL; ?>/admin">Admin</a></li>
            <li><a href="<?php echo BASE_URL; ?>/login">Iniciar Sesión</a></li>
            </ul>
        </nav>
    </header>

    <main>